cursor            #83d2e4
cursor_text_color #00363e

foreground            #dee3e5
background            #090f10
selection_foreground  #1c3439
selection_background  #b2cbd1
url_color             #b2cbd1

#: black 000000 767676
color0  #0e1416
color8  #303637
#: red cc0403 f2201f
color1  #6f5c04
color9  #f7ce15
#: green 19cb00 23fd00
color2  #b2cbd1
color10 #cde7ed
#: yellow cecb00 fffd00
color3  #bcc5eb
color11 #dbe1ff
#: blue 0d73cc 1a8fff
color4  #004e5a
color12 #83d2e4
#: magenta cb1ed1 fd28ff
color5  #334a50
color13 #b2cbd1
#: cyan 0dcdcd 14ffff
color6  #3d4665
color14 #bcc5eb
#: white dddddd ffffff
color7  #bfc8cb
color15 #dee3e5

mark1_foreground #001f25
mark1_background #a3eeff
mark2_foreground #051f24
mark2_background #cde7ed
mark3_foreground #111a37
mark3_background #dbe1ff

active_tab_foreground #00363e
active_tab_background #83d2e4
inactive_tab_foreground #a3eeff
inactive_tab_background #004e5a

active_border_color #83d2e4
inactive_border_color #00363e
# bell_border_color #ff5a00
