#!/bin/bash

WALL_DIR="$HOME/Pictures/Wallpapers"

CWD="$(pwd)"

cd "$WALL_DIR" || exit

IFS=$'\n'

SELECTED_WALL=$(for a in *.jpg *.png; do echo -en "$a\0icon\x1f$a\n" ; done | rofi -dmenu -p "Switch Theme" -theme ~/.config/rofi/launchers/type-3/style-wallpaper.rasi )

if [ -n "$SELECTED_WALL" ]; then
  ~/scripts/walset-backend "$SELECTED_WALL"
fi

cd "$CWD" || exit
